package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import config.ConexionDB;
import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class IndexFXMLController {
	@FXML
	private RadioButton rBtnPersonas;
	@FXML
	private RadioButton rBtnCalculos;
	@FXML
	private RadioButton rBtnSubinformes;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;

	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		if (rBtnPersonas.isSelected()) {
			try {
				ConexionDB con = new ConexionDB();
				JasperReport report = (JasperReport) JRLoader.loadObject(getClass().getResource("/reports/InformePersonas.jasper"));
				JasperPrint jprint = JasperFillManager.fillReport(report, null, con.getConexion());
				JasperViewer viewer = new JasperViewer(jprint, false);
				viewer.setVisible(true);
			} catch (JRException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		if (rBtnCalculos.isSelected()) {
			try {
				ConexionDB con = new ConexionDB();
				JasperReport report = (JasperReport) JRLoader.loadObject(getClass().getResource("/reports/Calculos.jasper"));
				JasperPrint jprint = JasperFillManager.fillReport(report, null, con.getConexion());
				JasperViewer viewer = new JasperViewer(jprint, false);
				viewer.setVisible(true);
			} catch (JRException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		if (rBtnSubinformes.isSelected()) {
			try {
				ConexionDB con = new ConexionDB();
				JasperReport report = (JasperReport) JRLoader.loadObject(getClass().getResource("/reports/Subinformes.jasper"));
				JasperPrint jprint = JasperFillManager.fillReport(report, null, con.getConexion());
				JasperViewer viewer = new JasperViewer(jprint, false);
				viewer.setVisible(true);
			} catch (JRException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
}
