package controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import model.Libro;

import java.net.URL;
import java.util.ResourceBundle;

import dao.LibroDAO;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class GestionLibroFXMLController implements Initializable{
	@FXML
	private TextField txtTitulo;
	@FXML
	private TextField txtCodigo;
	@FXML
	private TextField txtAutor;
	@FXML
	private TextField txtEditorial;
	@FXML
	private ComboBox <String> cmbBoxEstado;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;
	
	private ObservableList<String> data;
	private Libro l;
	private LibroDAO cLibro;

	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void setLibro (Libro lib) {
		l = lib;
	}
	
	public Libro getLibro () {
		return l;
	}
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		data = FXCollections.observableArrayList();
		data.addAll("Nuevo","Usado nuevo", "Usado seminuevo", "Usado estropeado", "Restaurado");
		cmbBoxEstado.setItems(data);
		
	}
}
