package controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import dao.AlumnoDAO;
import dao.LibroDAO;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;
import model.Alumno;
import model.Libro;

public class GestionPrestamosFXMLController implements Initializable{
	@FXML
	private ComboBox <Libro> cmbBoxLibro;
	@FXML
	private ComboBox <Alumno> cmbBoxAlumno;
	@FXML
	private Button btnCancelar;
	@FXML
	private Button btnAceptar;
	
	private ObservableList<Alumno> dataAlumno;
	private AlumnoDAO cAlumno;
	private ObservableList<Libro> dataLibro;
	private LibroDAO cLibro;

	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		cAlumno = new AlumnoDAO();
		cLibro = new LibroDAO ();
		
		cargarAlumnos();
		cargarLibros();
		
	}
	
	private void cargarAlumnos () {
		dataAlumno = FXCollections.observableArrayList();
		cmbBoxAlumno.setItems(dataAlumno);
		ArrayList<Alumno> lstAlumnos = cAlumno.selectAlumnos();
		
		dataAlumno.clear();
		dataAlumno.addAll(lstAlumnos);
	}
	
	private void cargarLibros () {
		dataLibro = FXCollections.observableArrayList();
		cmbBoxLibro.setItems(dataLibro);
		ArrayList <Libro> lstLibros = cLibro.selectLibrosDisponibles();
		
		dataLibro.clear();
		dataLibro.addAll(lstLibros);
	}
}
