package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class GestionAlumnoFXMLController {
	@FXML
	private TextField txtFieldDni;
	@FXML
	private TextField txtFieldNombre;
	@FXML
	private TextField txtFieldApellido1;
	@FXML
	private TextField txtFieldApellido2;
	@FXML
	private Button btnAceptar;
	@FXML
	private Button btnCancelar;
	
	private boolean crear = true;

	// Event Listener on Button[#btnAceptar].onAction
	@FXML
	public void aceptar(ActionEvent event) {
		if (crear) {
			
		}
	}
	// Event Listener on Button[#btnCancelar].onAction
	@FXML
	public void cancelar(ActionEvent event) {
		// TODO Autogenerated
	}
}
