package controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import dao.AlumnoDAO;
import dao.LibroDAO;
import dao.PrestamoDAO;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.MenuItem;

import javafx.scene.control.ComboBox;

import javafx.scene.input.MouseEvent;
import model.Alumno;
import model.Libro;
import model.Prestamo;

public class VentanaPrestamosFXMLController implements Initializable{
	@FXML
	private ListView <Prestamo> lstPrestamos;
	@FXML
	private MenuItem mnuCrear;
	@FXML
	private MenuItem mnuEditar;
	@FXML
	private MenuItem mnuDevolver;
	@FXML
	private ComboBox <Alumno> cmbBoxAlumnos;
	@FXML
	private Button btnCrear;
	@FXML
	private Button btnEditar;
	@FXML
	private Button btnDevolver;
	
	private ObservableList<Prestamo> dataPrestamo;
	private ObservableList<Alumno> dataAlumno;
	
	private PrestamoDAO cPrestamo;
	private AlumnoDAO cAlumno;
	
	private int iSeleccionado = -1;
	private Prestamo p;

	// Event Listener on ListView[#lstPrestamos].onMouseClicked
	@FXML
	public void seleccionarFila(MouseEvent event) {
		mnuEditar.setDisable(false);
		mnuDevolver.setDisable(false);
		btnDevolver.setDisable(false);
		btnEditar.setDisable(false);
		
		iSeleccionado= lstPrestamos.getSelectionModel().getSelectedIndex();
		p = lstPrestamos.getSelectionModel().getSelectedItem();
	}
	// Event Listener on ComboBox[#cmbBoxAlumnos].onAction
	@FXML
	public void filtrarPorAlumno(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	// Event Listener on MenuItem[#mnuCrear].onAction
	@FXML
	public void crearPrestamoMnu(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mnuEditar].onAction
	@FXML
	public void editarPrestamoMnu(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#mnuDevolver].onAction
	@FXML
	public void devolverPrestamoMnu(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCrear].onAction
	@FXML
	public void crearPrestamoBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEditar].onAction
	@FXML
	public void editarPrestamoBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDevolver].onAction
	@FXML
	public void devolverPrestamoBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		cPrestamo = new PrestamoDAO();
		cAlumno =  new AlumnoDAO();
		
		cargarPrestamos();
		cargarAlumnos();
	}
	
	private void cargarPrestamos () {
		btnEditar.setDisable(true);
		btnDevolver.setDisable(true);
		
		dataPrestamo= FXCollections.observableArrayList();
		lstPrestamos.setItems(dataPrestamo);
		ArrayList <Prestamo> lstPrestamos = cPrestamo.selectPrestamos();
		
		dataPrestamo.clear();
		dataPrestamo.addAll(lstPrestamos);
		
	}
	
	private void cargarAlumnos () {
		dataAlumno = FXCollections.observableArrayList();
		cmbBoxAlumnos.setItems(dataAlumno);
		ArrayList<Alumno> lstAlumnos = cAlumno.selectAlumnos();
		
		dataAlumno.clear();
		dataAlumno.addAll(lstAlumnos);
	}
	
	
}
