package controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.collections.transformation.FilteredList;
import javafx.collections.transformation.SortedList;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.MenuItem;

import javafx.scene.input.MouseEvent;
import model.Alumno;
import model.Libro;
import modelo.Persona;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class VentanaPrincipalFXMLController implements Initializable{
	@FXML
	private TextField txtFieldAlumno;
	@FXML
	private Button btnCrearAlumno;
	@FXML
	private Button btnEditarAlumno;
	@FXML
	private Button btnBorrarAlumno;
	@FXML
	private ListView <Alumno> lstAlumno;
	@FXML
	private MenuItem menuCrearAlumno;
	@FXML
	private MenuItem menuEditarAlumno;
	@FXML
	private MenuItem menuBorrarAlumno;
	@FXML
	private TextField txtFieldLibros;
	@FXML
	private TableView<Libro> tblLibro;
	@FXML
	private TableColumn<Libro,Integer> colCodigoLibro;
	@FXML
	private TableColumn<Libro, String> colTitulo;
	@FXML
	private TableColumn <Libro, String>colAutorLibro;
	@FXML
	private TableColumn <Libro, String>colEstadoLibro;
	@FXML
	private MenuItem menuCrearLibro;
	@FXML
	private MenuItem menuEditarLibro;
	@FXML
	private MenuItem menuBorrarLibro;
	@FXML
	private Button btnCrearLibro;
	@FXML
	private Button btnEditarLibro;
	@FXML
	private Button btnBorrarLibro;
	@FXML
	private Button btnPrestar;
	@FXML
	private MenuItem menuGestionarPrestamo;
	@FXML
	private MenuItem menuGestionarHistorico;
	
	
	private ObservableList<Libro> dataLibro;
	private int iSeleccionadoLibro=-1;
	
	private Libro l;

	// Event Listener on Button[#btnCrearAlumno].onAction
	@FXML
	public void crearAlumnoBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEditarAlumno].onAction
	@FXML
	public void editarAlumnoBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBorrarAlumno].onAction
	@FXML
	public void borrarAlumnoBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ListView[#lstAlumno].onMouseClicked
	@FXML
	public void seleccionarFilaLst(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#menuCrearAlumno].onAction
	@FXML
	public void crearAlumno(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#menuEditarAlumno].onAction
	@FXML
	public void editarAlumno(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#menuBorrarAlumno].onAction
	@FXML
	public void borrarAlumno(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TableView[#tblLibro].onMouseClicked
	@FXML
	public void seleccionarFilaTbl(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#menuCrearLibro].onAction
	@FXML
	public void crearLibro(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#menuEditarLibro].onAction
	@FXML
	public void editarLibro(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#menuBorrarLibro].onAction
	@FXML
	public void borrarLibro(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCrearLibro].onAction
	@FXML
	public void crearLibroBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEditarLibro].onAction
	@FXML
	public void editarLibroBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBorrarLibro].onAction
	@FXML
	public void borrarLibroBtn(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPrestar].onAction
	@FXML
	public void realizarPrestamo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#menuGestionarPrestamo].onAction
	@FXML
	public void gestionarPrestamo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#menuGestionarHistorico].onAction
	@FXML
	public void gestionarHistorico(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		dataLibro = FXCollections.observableArrayList();
		tblLibro.setItems(dataLibro);
		colCodigoLibro.setCellValueFactory(new PropertyValueFactory<Libro, Integer>("Codigo"));
		colTitulo.setCellValueFactory(new PropertyValueFactory<Libro, String>("Titulo"));
		colAutorLibro.setCellValueFactory(new PropertyValueFactory<Libro, String>("Autor"));
		colEstadoLibro.setCellValueFactory(new PropertyValueFactory<Libro, String>("Estado"));
		btnEditarLibro.setDisable(true);
		btnBorrarLibro.setDisable(true);
		
		
		
		//Filtro
		FilteredList<Persona> filteredData = new FilteredList<>(data, p -> true);
		
		
		txtFiltro.textProperty().addListener((observable, oldValue, newValue) -> {
			filteredData.setPredicate(person -> {
				
				if (newValue == null || newValue.isEmpty()) {
					return true;
				}
				
				
				String lowerCaseFilter = newValue.toLowerCase();
				
				if (person.getNombre().toLowerCase().contains(lowerCaseFilter)) {
					return true;
				} else if (person.getApellidos().toLowerCase().contains(lowerCaseFilter)) {
					return true;
				}
				return false; 
			});
		});
		

		SortedList<Persona> sortedData = new SortedList<>(filteredData);
		

		sortedData.comparatorProperty().bind(tblPersona.comparatorProperty());
		

		tblPersona.setItems(sortedData);
		
	}
}
