package controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import model.Alumno;
import model.Historico;
import model.Libro;

import java.net.URL;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.ResourceBundle;

import dao.AlumnoDAO;
import dao.HistoricoDAO;
import dao.LibroDAO;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class VentanaHistoricoFXMLController implements Initializable{
	@FXML
	private TextField txtFiltro;
	@FXML
	private ComboBox <Libro> cmbBoxLibro;
	@FXML
	private ComboBox <Alumno> cmbBoxAlumno;
	@FXML
	private TableView <Historico> tblHistorico;
	@FXML
	private TableColumn <Historico, Integer> colId;
	@FXML
	private TableColumn <Historico, String> colDni;
	@FXML
	private TableColumn<Historico, Integer> colLibro;
	@FXML
	private TableColumn <Historico, LocalDate> colFechaPrestamo;
	@FXML
	private TableColumn <Historico, LocalDate> colFechaDev;
	
	private ObservableList<Historico> dataHistorico;
	private HistoricoDAO cHistorico;
	
	private ObservableList <Libro> dataLibro;
	private LibroDAO cLibro;
	
	private ObservableList<Alumno> dataAlumno;
	private AlumnoDAO cAlumno;

	// Event Listener on ComboBox[#cmbBoxLibro].onAction
	@FXML
	public void filtrarLibro(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cmbBoxAlumno].onAction
	@FXML
	public void filtrarAlumno(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		
		cargarLibros();
		cargarAlumnos();
		cargarHistorico();
	}
	
	private void cargarLibros () {
		cLibro = new LibroDAO();
		dataLibro = FXCollections.observableArrayList();
		cmbBoxLibro.setItems(dataLibro);
		ArrayList <Libro> lstLibros = cLibro.selectLibrosDisponibles();
		
		dataLibro.clear();
		dataLibro.addAll(lstLibros);
	}
	
	private void cargarAlumnos() {
		cAlumno = new AlumnoDAO();
		
		dataAlumno = FXCollections.observableArrayList();
		cmbBoxAlumno.setItems(dataAlumno);
		ArrayList<Alumno> lstAlumnos = cAlumno.selectAlumnos();
		
		dataAlumno.clear();
		dataAlumno.addAll(lstAlumnos);
	}
	
	private void cargarHistorico() {
		cHistorico = new HistoricoDAO();
		dataHistorico = FXCollections.observableArrayList();
		tblHistorico.setItems(dataHistorico);
		colId.setCellValueFactory(new PropertyValueFactory<Historico, Integer>("ID"));
		colDni.setCellValueFactory(new PropertyValueFactory<Historico, String>("DNI"));
		colLibro.setCellValueFactory(new PropertyValueFactory<Historico, Integer>("Libro"));
		colFechaPrestamo.setCellValueFactory(new PropertyValueFactory<Historico, LocalDate>("Fecha Prestamo"));
		colFechaDev.setCellValueFactory(new PropertyValueFactory<Historico, LocalDate>("Fecha Devolucion"));
		
		ArrayList<Historico> lstHistorico = cHistorico.selectHistoricos();
		dataHistorico.clear();
		dataHistorico.addAll(lstHistorico);
		
	}
}
